services:
    postgres:
        image: postgres:16
        container_name: photo-prank-bot_postgres
        environment:
            POSTGRES_USER: "photo-prank-bot"
            POSTGRES_PASSWORD: "photo-prank-bot"
            POSTGRES_DB: "photo-prank-bot"
        ports:
            - "5432:5432"
        volumes:
            - postgres:/data/postgres

volumes:
    postgres:
